### PR TITLE
Switch to tzfpy

### PR DESCRIPTION
**Pull request by k3vmcd**
Workaround timezonefinder build issues by switching to tzfpy. See PR #3 for more info.

### CODE REVIEW

**Comment by k3vmcd** [comment]
This probably works, but requires user to install Rust build tools as a prerequisite, even on HAOS. This is not preferable. As such, I am closing this PR. Please note, this code is **untested** as I did not complete the tzfpy Rust build.

**Comment by ringsaturn** [comment]
Hi, do you know which wheel file is required to support HAOS?

**Comment by k3vmcd** [comment]
> Hi, do you know which wheel file is required to support HAOS?

@ringsaturn This is the error message in the logs. HAOS doesn't include the build tools to compile tzfpy by default.

`Unable to install package git+https://github.com/ringsaturn/tzfpy@main#tzfpy==0.15.3: error: subprocess-exited-with-error × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Cargo, the Rust package manager, is not installed or is not on PATH. This package requires Rust and Cargo to compile extensions. Install it through the system's package manager or via https://rustup.rs/ Checking for Rust toolchain.... [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.`

**Comment by k3vmcd** [comment]
@ringsaturn Also, in case you were wondering, HAOS can't find the tzfpy package using the normal way to require tzfpy like this in manifest.json:
` "requirements": [ "tzfpy==0.15.3" ],`

This gives the error:
`Unable to install package tzfpy==0.15.3: ERROR: Could not find a version that satisfies the requirement tzfpy==0.15.3 (from versions: none) ERROR: No matching distribution found for tzfpy==0.15.3`

**Comment by ringsaturn** [comment]
@k3vmcd Seems pip found no matched wheels and used source code to build. Can you provide some information so I could try to add new wheels to tzfpy for this case?

- Python version
- OS Version
- CPU Arch
- Debug info `pip debug --verbose`
- Error messages from `pip download tzfpy --only-binary=:all:`

**Pull request closed without merging**
